[theme]
base = "dark"
primaryColor = "#00f0ff"
backgroundColor = "#08080c"
secondaryBackgroundColor = "#0f111a"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
